# From: https://rohitgupta.xyz/blog/keeping-python-code-clean-with-pre-commit-hooks-black-flake8-and-isort/

repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      exclude: ^tests/
-   repo: local
    hooks:
    - id: spellcheck
      name: spellcheck
      entry: ./.spellcheck.sh
      language: system
      types_or: [python, markdown]