name: algopytest
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pre-commit
  - pytest
  - python
  - setuptools
  - sphinx<6
  - m2r2
  - sphinx_rtd_theme
  - twine
  - typing_extensions
  - pip:
    - py-algorand-sdk
    - pyteal