name: algopytest
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.3.1
  - pre-commit=2.17.0
  - pytest=7.0.0
  - python=3.10.2
  - setuptools=60.5.0
  - sphinx=4.4.0
  - m2r2=0.3.2
  - sphinx_rtd_theme=1.0.0
  - pip:
    - py-algorand-sdk==1.9.0
    - pyteal==0.9.1
