name: AlgoPytest Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-integration-tests:
    defaults:
      run:
        shell: bash -l {0}  
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]  
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: algopytest
          environment-file: ./environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          auto-update-conda: true          

      - name: Install AlgoPytest
        run: pip install .
          
      - name: List conda information
        run: |
          conda info
          conda list

      - name: Test Algo-Recurring-Payments Unittests
        run: |
          # Set the necessary environment variables for AlgoPytest
          export SANDBOX_DIR=$(pwd)/../sandbox
          export INITIAL_FUNDS_ACCOUNT=$(../sandbox/sandbox goal account list | awk '{print $3}' | head -n 1)
          export PYTHON_PATH=$(pwd)/demos/algo-recurring-payments/assets
          pytest ./demos/algo-recurring-payments/ -vx