name: AlgoPytest Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-integration-tests:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]  
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: algopytest
          environment-file: ./environment.yml
          python-version: ${{ matrix.python-version }}        

      - name: Clone Algorand Sanbox
        run: cd .. && git clone https://github.com/algorand/sandbox.git
        
      - name: Run Algorand Sandbox
        shell: 'script -q -e -c "bash {0}"' # hacky hack to make TTY work
        run: cd ../sandbox && ./sandbox up dev -v

      - name: Test Algo-Recurring-Payments Unittests
        run: |
          # Set the necessary environment variables for AlgoPytest
          export SANDBOX_DIR=$(pwd)/../sandbox
          export INITIAL_FUNDS_ACCOUNT=$(../sandbox/sandbox goal account list | awk '{print $3}' | head -n 1)
          export PYTHON_PATH=$(pwd)/demos/algo-recurring-payments/assets
          pytest ./demos/algo-recurring-payments/ -vx