name: AlgoPytest Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.8", "3.9", "3.10" ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python }}"
      - name: Test Python version
        run: |
          installed="$(python --version)"
          expected="${{ matrix.python }}"
          echo $installed
          [[ $installed =~ "Python ${expected}" ]] && echo "Configured Python" || (echo "Failed to configure Python" && exit 1)
      - name: Clone Algorand Sanbox
        run: cd .. && git clone https://github.com/algorand/sandbox.git
      - name: Run Algorand Sandbox
        shell: 'script -q -e -c "bash {0}"' # hacky hack to make TTY work
        run: cd ../sandbox && ./sandbox up dev -v